version: "3.8"

services:
  app: 
    build:
        context: .
        dockerfile: docker/dev.Dockerfile 
    image: nextech:latest
    container_name: nextech
    ports:
      - "3000:3000" 
    volumes:
      - .:/app
