services:
  app: 
    image: nextech:latest
    container_name: nextech
    build:
        context: .
        dockerfile: docker/dev.Dockerfile 
    ports:
      - "3000:3000" 
    volumes:
      - .:/app:rw
    networks:
      - net

networks:
  net:

